"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { BarChart3, LayoutDashboard, LayoutGrid, LogOut, Menu, Package, Save, Settings, ShoppingBag, Star, Tag, Users, X } from "lucide-react";
import { getSiteSettings, saveAllAdminData } from "@/lib/data";

const nav = [
  ["/admin/dashboard", "Dashboard", LayoutDashboard], ["/admin/orders", "Orders", ShoppingBag], ["/admin/products", "Products", Package], ["/admin/categories", "Categories", LayoutGrid], ["/admin/collections", "Collections", LayoutGrid], ["/admin/customers", "Customers", Users], ["/admin/analytics", "Analytics", BarChart3], ["/admin/coupons", "Coupons", Tag], ["/admin/reviews", "Reviews", Star], ["/admin/settings", "Settings", Settings],
] as const;

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  const router = useRouter(); const pathname = usePathname(); const [ready, setReady] = useState(pathname === "/admin"); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const settings = getSiteSettings();
  useEffect(() => { if (pathname === "/admin") return; void fetch("/api/auth/session").then((response) => response.json()).then(({ user }) => { if (user?.role !== "admin") router.replace("/admin"); else setReady(true); }).catch(() => router.replace("/admin")); }, [pathname, router]);
  if (!ready) return <div className="flex min-h-screen items-center justify-center bg-[#f7f7f4]"><div className="h-6 w-6 animate-spin rounded-full border-2 border-[#171717] border-t-transparent" /></div>;
  if (pathname === "/admin") return <>{children}</>;
  return <div data-admin-theme="light" className="min-h-screen bg-[#f7f7f4] text-[#171717]"><aside className={`fixed inset-y-0 left-0 z-40 w-64 border-r border-black/10 bg-white transition-transform md:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="border-b border-black/10 px-6 py-7"><Link href="/" className="text-2xl font-bold tracking-[-.08em]">9<span className="text-[#94ac29]">TEEN</span></Link><p className="mt-1 text-[10px] font-bold uppercase tracking-[.2em] text-[#898b83]">Control room</p></div><nav className="space-y-1 p-4">{nav.map(([href, label, Icon]) => <Link href={href} key={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold transition ${pathname === href ? "bg-[#c9ef45]" : "text-[#666860] hover:bg-[#f1f1ec]"}`}><Icon className="h-4 w-4" />{label}</Link>)}</nav><div className="absolute bottom-5 left-4 right-4"><button onClick={async () => { await fetch("/api/auth/logout", { method: "POST" }); router.push("/admin"); }} className="flex w-full items-center justify-center gap-2 rounded-xl border border-black/10 px-4 py-3 text-sm font-semibold text-[#666860] hover:bg-[#f1f1ec]"><LogOut className="h-4 w-4" />Sign out</button></div></aside>{open && <button aria-label="Close menu" className="fixed inset-0 z-30 bg-black/20 md:hidden" onClick={() => setOpen(false)} /> }<div className="md:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center gap-3 border-b border-black/10 bg-[#f7f7f4]/90 px-4 backdrop-blur sm:px-8"><button aria-label="Open menu" onClick={() => setOpen(!open)} className="rounded-lg border border-black/10 bg-white p-2 md:hidden">{open ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</button><p className="text-xs font-bold uppercase tracking-[.16em] text-[#777870]">{nav.find(([href]) => href === pathname)?.[1] || "Admin"}</p><div className="ml-auto flex items-center gap-3"><button disabled={saving} onClick={async () => { setSaving(true); saveAllAdminData(); setNotice("Saved to Convex"); setTimeout(() => setNotice(""), 3500); setSaving(false); }} className="inline-flex items-center gap-2 rounded-full bg-[#171717] px-4 py-2 text-xs font-bold text-white hover:bg-[#9bb42e] hover:text-black"><Save className="h-3.5 w-3.5" />{saving ? "Saving" : "Save all"}</button><Link href="/" className="hidden text-xs font-semibold text-[#777870] sm:block">View store</Link></div></header>{notice && <div className="fixed right-5 top-20 z-50 rounded-xl bg-[#c9ef45] px-4 py-3 text-xs font-bold shadow-lg">{notice}</div>}<main className="min-h-[calc(100vh-4rem)] p-4 sm:p-8">{children}</main></div></div>;
}
