"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, EyeOff, Lock, Shield } from "lucide-react";

export default function AdminLogin() {
  const router = useRouter(); const [needsSetup, setNeedsSetup] = useState(false); const [loading, setLoading] = useState(false); const [show, setShow] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ email: "", password: "", name: "Store administrator", phone: "0000000000", address: "Store office", city: "Kathmandu", setupKey: "" });
  useEffect(() => { void Promise.all([fetch("/api/auth/session").then(r => r.json()), fetch("/api/auth/admin/availability").then(r => r.json())]).then(([session, availability]) => { if (session.user?.role === "admin") router.replace("/admin/dashboard"); else setNeedsSetup(Boolean(availability.needsSetup)); }).catch(() => setError("Unable to connect to the authentication service.")); }, [router]);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const endpoint = needsSetup ? "/api/auth/admin/setup" : "/api/auth/login"; const payload = needsSetup ? form : { email: form.email, password: form.password, requiredRole: "admin" }; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setError(result.error || "Unable to sign in."); router.push("/admin/dashboard"); router.refresh(); }
  return <main className="flex min-h-screen items-center justify-center bg-[#11110f] p-4"><section className="w-full max-w-md rounded-[2rem] border border-white/10 bg-white/[0.04] p-7 text-white shadow-2xl backdrop-blur sm:p-9"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#d8522b]/15"><Shield className="h-6 w-6 text-[#f36b43]" /></div><div className="mt-6 text-center"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-white/45">9TEEN control room</p><h1 className="mt-2 text-3xl font-bold tracking-[-.05em]">{needsSetup ? "Set up your admin" : "Administrator sign in"}</h1><p className="mt-3 text-sm leading-relaxed text-white/55">{needsSetup ? "Create the first protected administrator account for this Convex deployment." : "Use your administrator email and password to continue."}</p></div><form onSubmit={submit} className="mt-8 space-y-4">{needsSetup && <><label className="block text-xs font-semibold text-white/55">SETUP KEY<input value={form.setupKey} onChange={e => setForm({ ...form, setupKey: e.target.value })} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-3.5 py-3 text-sm outline-none focus:border-[#d8522b]" required /></label><label className="block text-xs font-semibold text-white/55">DISPLAY NAME<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-3.5 py-3 text-sm outline-none focus:border-[#d8522b]" required /></label></>}<label className="block text-xs font-semibold text-white/55">EMAIL<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-3.5 py-3 text-sm outline-none focus:border-[#d8522b]" required /></label><label className="block text-xs font-semibold text-white/55">PASSWORD<div className="relative mt-2"><input type={show ? "text" : "password"} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} className="w-full rounded-xl border border-white/15 bg-black/20 px-3.5 py-3 pr-11 text-sm outline-none focus:border-[#d8522b]" required /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-3 text-white/50">{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></label>{error && <p className="rounded-xl bg-red-500/10 px-3 py-2.5 text-xs text-red-300">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-full bg-[#d8522b] py-3.5 text-sm font-bold text-white transition hover:bg-[#ed6840] disabled:opacity-60"><Lock className="h-4 w-4" />{loading ? "Please wait…" : needsSetup ? "Create administrator" : "Sign in securely"}</button></form></section></main>;
}
